config/routes.rb
Rails.application.routes.draw do

  root 'main#index'
  get 'about' => 'main#about', as: :about

  get 'sessions/new'
  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'

  delete 'sessions/destroy'
  get 'logout' => 'sessions#destroy' , as: :logout

  resources :users
  get 'signup' => 'users#new', as: :signup

  resources :posts
  get "posts/:id/comments" => "posts#comments", as: :post_comments
  post "posts/:id/comments" => "posts#create_comment"

  get 'comments/:id/comments/new' => 'comments#new_comment', as: :new_comment_comment
  post 'comments/:id/comments' => 'comments#create_comment', as: :comment_comments
  post "comments/:id/votes" => "comments#create_vote", as: :comment_create_vote
  post "posts/:id/votes" => "posts#create_vote", as: :post_create_vote

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  has_many :votes, as: :voteable
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :votes, as: :voteable
end

app/models/user.rb
class User < ActiveRecord::Base

    has_secure_password

    has_many :posts
    has_many :comments
    has_many :votes

    validates :email,
    presence: true,
    uniqueness: {case_sensitive: false}

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_user

  def current_user
    @current_user ||= session[:user]
  end

  def is_authenticated?
    if !current_user
      flash[:danger]='You must be logged in to access that page.'
      redirect_to login_path
      false
    else
      true
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #before_action :locate_comment, only: [:new, :create_vote]

  def create_comment
    return unless is_authenticated?
    user = User.find_by_id(@current_user['id'])
    post = Post.find_by_id(params[:id])
    user.comments << post.comments.create({body:params[:comment][:body]})
    redirect_to post_comments_path
    #render json: params
  end
  def new_comment
    @parent_comment = Comment.find_by_id(params[:id])
    @comment = Comment.new
  end
  def create_vote
      return unless is_authenticated?
      User.find_by_id(@current_user['id']).votes << Comment.find_by_id(params[:id]).votes.create
      redirect_to(:back)

      #ajax
      # respond_to do |format|
      #   format.json { render json: {result: !existing_vote,votes:comment.votes.length} }
      #   format.html {redirect_to post_comments_path(parent_post(comment))}

      # render json: params[:id]
      # redirect_to "/"

      #if existing vote
      #flash error
      #else
      #run vote line
      #end
      #redirect to post path
  end

  private
  # def locate_comment
  #   redirect_to '/404.html' unless  @post = Post.find_by_id(params[:id])
  # end
  def parent_post comment
    return comment if comment.class == Post
    return parent_post(comment.commentable)
  end


end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        if @current_user
            return render 'main/loggedin_index'
        end
    end

    def about
        @post = Post.last

          respond_to do |format|
          format.json
          format.xml
          format.html
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = Post.all
        @votes = Vote.all

        respond_to do |format|
          format.json {render json: @posts}
          format.xml {render xml: @posts}
          format.html
        end

        # render json: @posts
    end

    def show
    end

    def new
        @post = Post.new
    end

    def create
      return unless is_authenticated?
      user = User.find_by_id(@current_user['id'])
      @post = user.posts.create post_params
      if @post.errors.any?
        render :new
      else
        flash[:success] = 'Post added'
        redirect_to posts_path
      end

    end

    def edit
    end

    def update
    end

    def destroy
    end

    def comments
      @post = Post.find_by_id(params[:id])
      @comment = Comment.new
    end
    def create_comment
      return unless is_authenticated?
      user = User.find_by_id(@current_user['id'])
      post = Post.find_by_id(params[:id])
      user.comments << post.comments.create({body:params[:comment][:body]})
      redirect_to post_comments_path
      #render json: params
    end


    def create_vote
      User.find_by_id(@current_user['id']).votes << Post.find_by_id(params[:id]).votes.create
      redirect_to(:back)

                  #ajax  this needs fixing...
      # respond_to do |format|
      #   format.json { render json: {result: !existing_vote,votes:post.votes.length} }
      #   format.html {redirect_to post_posts_path}
      # end

    end


  private

  def post_params
    params.require(:post).permit(:title,:link)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:user][:email])
    if user
        if user.try(:authenticate,params[:user][:password])
            session[:user] = {:id => user.id, :name => user.name}
            flash[:success]='You have been logged in'
            redirect_to root_path
        else
            flash[:danger]='Invalid password'
            redirect_to login_path
        end
    else
        flash[:danger]='Unknown email please signup.'
        redirect_to login_path
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.errors.any?
      render :new
    else
      flash[:success] = 'User has been created. You can now log in.'
      redirect_to login_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def format_creation_time item
    if item.created_at > Time.now.beginning_of_day
        "#{time_ago_in_words(item.created_at)} ago"
    else
        item.created_at.strftime("%e %b %Y %H:%M:%S%p")
    end   
  end 

end

app/helpers/posts_helper.rb
module PostsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LinkBoardLab</title>

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Teh HaXoR N3ws!1</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
            <li><%= link_to "Posts", posts_path %></li>
              <li><%= link_to "About", about_path %></li>
              <% if @current_user %>
                <li><%= link_to "Create Post", new_post_path %></li>
              <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if @current_user %>
                <li><a href="">Hello, <%= @current_user['name'] %></a></li>
                <li><%= link_to 'logout',logout_path %></li>
              <% else %>
                <li><%= link_to 'signup', signup_path %></li>
                <li><%= link_to 'login', login_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
        <% if flash.any? %>
          <% flash.each do |key,val| %>
            <div class="alert alert-<%= key %>"><%= val %></div>
          <% end %>
        <% end %>
    </div>
    <div class="container">
        <%= yield %>
    </div>

</body>
</html>

app/views/main/about.html.erb
<h3>About</h3>

<p>this is the about page</p>

Last post was posted <%= format_creation_time @post %>

app/views/main/about.json.erb
{
  "page":"this is the about page",
  "last_post":"<%= format_creation_time @post %>"
}

app/views/main/about.xml.erb
<page>
  <title> About Page </title>
  <last_post><%= format_creation_time @post %></last_post>
</page>

app/views/main/index.html.erb
<h1>Home page</h1>

app/views/main/loggedin_index.html.erb
<h1>Welcome back, <%= session[:user]['name'] %></h1>

app/views/posts/_comment.html.erb
<div class="btn-group test">
    <ul class = "list-inline col-md-12">
        <li> <%=button_to "&#8682".html_safe, comment_create_vote_path(comment), :class => "btn btn-default btn-xs ajax-vote"%></li>
        <li> <em class="vote-count"><%=comment.votes.count%> </em></li>
        <li> <%= comment.user ? comment.user.name : "Unknown" %> <small><%= format_creation_time comment %></small> </li>
        <li> <%= comment.body %> </li>
        <li>
    <% unless comment.comments.empty? %>
            <%= render :partial => 'comment', :collection => comment.comments %>
    <% end %>
        </li>
    </ul>
</div>

app/views/posts/comments.html.erb
<h1> <%= link_to @post.title, @post.link, :target => "_blank" %> </h1>
<br><br>

<h4>Post a Comment</h4>

<%= form_for @comment, url: post_comments_path, html: {class: "form"} do |f| %>
  <div class="form-group">
    <%= f.text_area :body, :placeholder => "Enter your comment", :class=>"form-control" %>
  </div>
  <div>
    <%= f.submit "Post Comment" %>
<% end %>
  </div>
<br>

<ul class="comment_list">
    <%= render :partial => 'comment', :collection => @post.comments %>
</ul>

app/views/posts/edit.html.erb
edit

app/views/posts/index.html.erb
<h3>Latest posts</h3>
<table class="table">
<tr>
    <th>Upvote</th>
    <th>Score</th>
    <th>Title</th>
    <th>User</th>
    <th>Posted</th>
    <th>Comments</th>
</tr>
<% if @posts.any? %>
    <% @posts.each do |post| %>
        <tr>
            <td><% if post.votes.where(user_id:@current_user['id']).any? %>
                    <%= button_to "&#8682".html_safe, post_create_vote_path(post), :class => "btn btn-default btn-xs disabled" %>
                <%else%>
                <%= button_to "&#8682".html_safe, post_create_vote_path(post), :class => "btn btn-default btn-xs ajax-vote" %>
                <%end%>
             </td>
            <td><span class="vote-count"><%= post.votes.length %>  </span>    </td>
            <td><%= link_to post.title,post.link, :target=>'_blank' %></td>
            <td><%= post.user ? post.user.name : 'Unknown' %></td>
            <td><%= format_creation_time post %> </td>
            <td><%= link_to "Comment", post_comments_path(post), :class => "btn btn-warning btn-sm"%></td>
        </tr>
    <% end %>
<% else %>
    <tr>
        <td>No posts</td>
    </tr>
<% end %>

app/views/posts/new.html.erb
<div class="row">
    <div class="col-md-4">
        <h3>Create New Post</h3>
        <%= form_for @post, html: {class: 'form'} do |f| %>
        <div class="form-group">
            <%= f.text_field :title, placeholder: 'Enter title' %>
        </div>
        <div class="form-group">
            <%= f.text_field :link, placeholder: 'Enter link url' %>
        </div>
        <%= f.submit 'Add Post', class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/posts/show.html.erb
<h1>Show Page</h1>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>New user signup</h1>

<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |error| %>
        <div class="alert alert-danger"><%= error %></div>
    <% end %>
<% end %>

<div class="row">
    <div class="col-md-4">
        <%= form_for @user, html: {class: 'form'} do |f| %>
            <div class="form-group">
                <%= f.text_field :email, :placeholder => 'E-mail address' %>
            </div>
            <div class="form-group">
                <%= f.text_field :name, :placeholder => 'Display name' %>
            </div>
            <div class="form-group">
                <%= f.password_field :password, :placeholder => 'Choose a password' %>
            </div>
            <%= f.submit 'signup', class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>